name: DP5
channels:
  - pytorch
  - dglteam
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=>3.10
  - pip
  - pip:
    - tensorflow[and-cuda]>=1.12.0
    - keras>=2.2.5
    - pandas
    - rdkit
    - scikit-learn
    - tqdm
